import { useState } from 'react';
import { Lightbulb, Sparkles, Loader2 } from 'lucide-react';
import { getAiInsights } from '../../api/client';
import './InsightsPanel.css';
import '../ai/ai-shared.css';

export default function InsightsPanel({ insights, personaId }) {
  const [aiInsights, setAiInsights] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const displayInsights = aiInsights || insights;

  const handleGenerate = () => {
    if (!personaId) return;
    setLoading(true);
    setError(null);
    getAiInsights(personaId)
      .then(data => setAiInsights(data.insights))
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  };

  if (!displayInsights || displayInsights.length === 0) return null;

  return (
    <div className="insights-section">
      <div className="ai-panel-header">
        <h3 className="section-title">Key Insights</h3>
        <button className="ai-generate-btn" onClick={handleGenerate} disabled={loading}>
          {loading ? (
            <><Loader2 size={14} className="spinning" /> Generating...</>
          ) : aiInsights ? (
            <><Sparkles size={14} /> Regenerate AI Insights</>
          ) : (
            <><Sparkles size={14} /> Generate AI Insights</>
          )}
        </button>
      </div>
      {error && <div className="ai-error">Failed to generate AI insights. Showing default insights.</div>}
      <div className="insights-card">
        {aiInsights && (
          <div className="ai-insights-badge">
            <Sparkles size={12} /> Generated by Snowflake AI_COMPLETE
          </div>
        )}
        {displayInsights.map((insight, i) => (
          <div key={i} className="insight-item">
            <Lightbulb size={14} className="insight-icon" />
            <span>{insight}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
